<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\Exception\LogicException;
use Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;
use Symfony\Component\DependencyInjection\ParameterBag\FrozenParameterBag;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class ProjectServiceContainer extends Container
{
    protected $parameters = [];
    protected \Closure $getService;

    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMap = [
            'Fusio\\Adapter\\Http\\Action\\HttpComposition' => 'getHttpCompositionService',
            'Fusio\\Adapter\\Http\\Action\\HttpLoadBalancer' => 'getHttpLoadBalancerService',
            'Fusio\\Adapter\\Http\\Action\\HttpProcessor' => 'getHttpProcessorService',
            'Fusio\\Adapter\\Http\\Action\\HttpRaw' => 'getHttpRawService',
            'Fusio\\Adapter\\Http\\Connection\\Http' => 'getHttpService',
            'Fusio\\Engine\\Test\\CallbackAction' => 'getCallbackActionService',
            'Fusio\\Engine\\Test\\CallbackConnection' => 'getCallbackConnectionService',
            'Fusio\\Engine\\Test\\EngineContainer' => 'getEngineContainerService',
            'actions' => 'getActionsService',
            'connections' => 'getConnectionsService',
            'generators' => 'getGeneratorsService',
            'payments' => 'getPaymentsService',
            'users' => 'getUsersService',
        ];

        $this->aliases = [];
    }

    public function compile(): void
    {
        throw new LogicException('You cannot compile a dumped container that was already compiled.');
    }

    public function isCompiled(): bool
    {
        return true;
    }

    public function getRemovedIds(): array
    {
        return [
            'Fusio\\Engine\\Action\\MemoryQueue' => true,
            'Fusio\\Engine\\Action\\QueueInterface' => true,
            'Fusio\\Engine\\Action\\Resolver\\DatabaseAction' => true,
            'Fusio\\Engine\\Action\\Resolver\\PhpClass' => true,
            'Fusio\\Engine\\Action\\Runtime' => true,
            'Fusio\\Engine\\Action\\RuntimeInterface' => true,
            'Fusio\\Engine\\Connector' => true,
            'Fusio\\Engine\\ConnectorInterface' => true,
            'Fusio\\Engine\\Dispatcher' => true,
            'Fusio\\Engine\\DispatcherInterface' => true,
            'Fusio\\Engine\\Factory\\Action' => true,
            'Fusio\\Engine\\Factory\\ActionInterface' => true,
            'Fusio\\Engine\\Factory\\Connection' => true,
            'Fusio\\Engine\\Factory\\ConnectionInterface' => true,
            'Fusio\\Engine\\Form\\ElementFactory' => true,
            'Fusio\\Engine\\Form\\ElementFactoryInterface' => true,
            'Fusio\\Engine\\Processor' => true,
            'Fusio\\Engine\\ProcessorInterface' => true,
            'Fusio\\Engine\\Repository\\ActionInterface' => true,
            'Fusio\\Engine\\Repository\\ActionMemory' => true,
            'Fusio\\Engine\\Repository\\AppInterface' => true,
            'Fusio\\Engine\\Repository\\AppMemory' => true,
            'Fusio\\Engine\\Repository\\ConnectionInterface' => true,
            'Fusio\\Engine\\Repository\\ConnectionMemory' => true,
            'Fusio\\Engine\\Repository\\UserInterface' => true,
            'Fusio\\Engine\\Repository\\UserMemory' => true,
            'Fusio\\Engine\\Response\\Factory' => true,
            'Fusio\\Engine\\Response\\FactoryInterface' => true,
            'Fusio\\Engine\\Worker\\ExecuteBuilder' => true,
            'Fusio\\Engine\\Worker\\ExecuteBuilderInterface' => true,
            'Monolog\\Handler\\NullHandler' => true,
            'Monolog\\Logger' => true,
            'Psr\\Log\\LoggerInterface' => true,
            'Psr\\SimpleCache\\CacheInterface' => true,
            'Symfony\\Component\\Cache\\Adapter\\ArrayAdapter' => true,
            'Symfony\\Component\\Cache\\Psr16Cache' => true,
        ];
    }

    /**
     * Gets the public 'Fusio\Adapter\Http\Action\HttpComposition' shared autowired service.
     *
     * @return \Fusio\Adapter\Http\Action\HttpComposition
     */
    protected static function getHttpCompositionService($container)
    {
        $a = ($container->privates['Fusio\\Engine\\Action\\Runtime'] ?? self::getRuntimeService($container));

        if (isset($container->services['Fusio\\Adapter\\Http\\Action\\HttpComposition'])) {
            return $container->services['Fusio\\Adapter\\Http\\Action\\HttpComposition'];
        }

        $instance = new \Fusio\Adapter\Http\Action\HttpComposition($a);

        if (isset($container->services['Fusio\\Adapter\\Http\\Action\\HttpComposition'])) {
            return $container->services['Fusio\\Adapter\\Http\\Action\\HttpComposition'];
        }

        return $container->services['Fusio\\Adapter\\Http\\Action\\HttpComposition'] = $instance;
    }

    /**
     * Gets the public 'Fusio\Adapter\Http\Action\HttpLoadBalancer' shared autowired service.
     *
     * @return \Fusio\Adapter\Http\Action\HttpLoadBalancer
     */
    protected static function getHttpLoadBalancerService($container)
    {
        $a = ($container->privates['Fusio\\Engine\\Action\\Runtime'] ?? self::getRuntimeService($container));

        if (isset($container->services['Fusio\\Adapter\\Http\\Action\\HttpLoadBalancer'])) {
            return $container->services['Fusio\\Adapter\\Http\\Action\\HttpLoadBalancer'];
        }

        $instance = new \Fusio\Adapter\Http\Action\HttpLoadBalancer($a);

        if (isset($container->services['Fusio\\Adapter\\Http\\Action\\HttpLoadBalancer'])) {
            return $container->services['Fusio\\Adapter\\Http\\Action\\HttpLoadBalancer'];
        }

        return $container->services['Fusio\\Adapter\\Http\\Action\\HttpLoadBalancer'] = $instance;
    }

    /**
     * Gets the public 'Fusio\Adapter\Http\Action\HttpProcessor' shared autowired service.
     *
     * @return \Fusio\Adapter\Http\Action\HttpProcessor
     */
    protected static function getHttpProcessorService($container)
    {
        $a = ($container->privates['Fusio\\Engine\\Action\\Runtime'] ?? self::getRuntimeService($container));

        if (isset($container->services['Fusio\\Adapter\\Http\\Action\\HttpProcessor'])) {
            return $container->services['Fusio\\Adapter\\Http\\Action\\HttpProcessor'];
        }

        $instance = new \Fusio\Adapter\Http\Action\HttpProcessor($a);

        if (isset($container->services['Fusio\\Adapter\\Http\\Action\\HttpProcessor'])) {
            return $container->services['Fusio\\Adapter\\Http\\Action\\HttpProcessor'];
        }

        return $container->services['Fusio\\Adapter\\Http\\Action\\HttpProcessor'] = $instance;
    }

    /**
     * Gets the public 'Fusio\Adapter\Http\Action\HttpRaw' shared autowired service.
     *
     * @return \Fusio\Adapter\Http\Action\HttpRaw
     */
    protected static function getHttpRawService($container)
    {
        $a = ($container->privates['Fusio\\Engine\\Action\\Runtime'] ?? self::getRuntimeService($container));

        if (isset($container->services['Fusio\\Adapter\\Http\\Action\\HttpRaw'])) {
            return $container->services['Fusio\\Adapter\\Http\\Action\\HttpRaw'];
        }

        $instance = new \Fusio\Adapter\Http\Action\HttpRaw($a);

        if (isset($container->services['Fusio\\Adapter\\Http\\Action\\HttpRaw'])) {
            return $container->services['Fusio\\Adapter\\Http\\Action\\HttpRaw'];
        }

        return $container->services['Fusio\\Adapter\\Http\\Action\\HttpRaw'] = $instance;
    }

    /**
     * Gets the public 'Fusio\Adapter\Http\Connection\Http' shared autowired service.
     *
     * @return \Fusio\Adapter\Http\Connection\Http
     */
    protected static function getHttpService($container)
    {
        return $container->services['Fusio\\Adapter\\Http\\Connection\\Http'] = new \Fusio\Adapter\Http\Connection\Http();
    }

    /**
     * Gets the public 'Fusio\Engine\Test\CallbackAction' shared autowired service.
     *
     * @return \Fusio\Engine\Test\CallbackAction
     */
    protected static function getCallbackActionService($container)
    {
        $a = ($container->privates['Fusio\\Engine\\Action\\Runtime'] ?? self::getRuntimeService($container));

        if (isset($container->services['Fusio\\Engine\\Test\\CallbackAction'])) {
            return $container->services['Fusio\\Engine\\Test\\CallbackAction'];
        }

        $instance = new \Fusio\Engine\Test\CallbackAction($a);

        if (isset($container->services['Fusio\\Engine\\Test\\CallbackAction'])) {
            return $container->services['Fusio\\Engine\\Test\\CallbackAction'];
        }

        return $container->services['Fusio\\Engine\\Test\\CallbackAction'] = $instance;
    }

    /**
     * Gets the public 'Fusio\Engine\Test\CallbackConnection' shared autowired service.
     *
     * @return \Fusio\Engine\Test\CallbackConnection
     */
    protected static function getCallbackConnectionService($container)
    {
        return $container->services['Fusio\\Engine\\Test\\CallbackConnection'] = new \Fusio\Engine\Test\CallbackConnection();
    }

    /**
     * Gets the public 'Fusio\Engine\Test\EngineContainer' shared autowired service.
     *
     * @return \Fusio\Engine\Test\EngineContainer
     */
    protected static function getEngineContainerService($container)
    {
        $a = ($container->privates['Fusio\\Engine\\Repository\\ActionMemory'] ??= new \Fusio\Engine\Repository\ActionMemory());
        $b = ($container->privates['Fusio\\Engine\\Repository\\ConnectionMemory'] ??= new \Fusio\Engine\Repository\ConnectionMemory());

        return $container->services['Fusio\\Engine\\Test\\EngineContainer'] = new \Fusio\Engine\Test\EngineContainer(($container->privates['Fusio\\Engine\\Factory\\Action'] ?? self::getActionService($container)), ($container->privates['Fusio\\Engine\\Action\\MemoryQueue'] ??= new \Fusio\Engine\Action\MemoryQueue()), $a, ($container->privates['Fusio\\Engine\\Factory\\Connection'] ?? self::getConnectionService($container)), $b, new \Fusio\Engine\Form\ElementFactory($a, $b));
    }

    /**
     * Gets the public 'actions' shared autowired service.
     *
     * @return \Fusio\Engine\Test\ProviderCollection
     */
    protected static function getActionsService($container)
    {
        return $container->services['actions'] = new \Fusio\Engine\Test\ProviderCollection(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['Fusio\\Engine\\Test\\CallbackAction'] ?? self::getCallbackActionService($container));
            yield 1 => ($container->services['Fusio\\Adapter\\Http\\Action\\HttpComposition'] ?? self::getHttpCompositionService($container));
            yield 2 => ($container->services['Fusio\\Adapter\\Http\\Action\\HttpLoadBalancer'] ?? self::getHttpLoadBalancerService($container));
            yield 3 => ($container->services['Fusio\\Adapter\\Http\\Action\\HttpProcessor'] ?? self::getHttpProcessorService($container));
            yield 4 => ($container->services['Fusio\\Adapter\\Http\\Action\\HttpRaw'] ?? self::getHttpRawService($container));
        }, 5));
    }

    /**
     * Gets the public 'connections' shared autowired service.
     *
     * @return \Fusio\Engine\Test\ProviderCollection
     */
    protected static function getConnectionsService($container)
    {
        return $container->services['connections'] = new \Fusio\Engine\Test\ProviderCollection(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['Fusio\\Engine\\Test\\CallbackConnection'] ??= new \Fusio\Engine\Test\CallbackConnection());
            yield 1 => ($container->services['Fusio\\Adapter\\Http\\Connection\\Http'] ??= new \Fusio\Adapter\Http\Connection\Http());
        }, 2));
    }

    /**
     * Gets the public 'generators' shared autowired service.
     *
     * @return \Fusio\Engine\Test\ProviderCollection
     */
    protected static function getGeneratorsService($container)
    {
        return $container->services['generators'] = new \Fusio\Engine\Test\ProviderCollection(new RewindableGenerator(fn () => new \EmptyIterator(), 0));
    }

    /**
     * Gets the public 'payments' shared autowired service.
     *
     * @return \Fusio\Engine\Test\ProviderCollection
     */
    protected static function getPaymentsService($container)
    {
        return $container->services['payments'] = new \Fusio\Engine\Test\ProviderCollection(new RewindableGenerator(fn () => new \EmptyIterator(), 0));
    }

    /**
     * Gets the public 'users' shared autowired service.
     *
     * @return \Fusio\Engine\Test\ProviderCollection
     */
    protected static function getUsersService($container)
    {
        return $container->services['users'] = new \Fusio\Engine\Test\ProviderCollection(new RewindableGenerator(fn () => new \EmptyIterator(), 0));
    }

    /**
     * Gets the private 'Fusio\Engine\Action\Resolver\DatabaseAction' shared autowired service.
     *
     * @return \Fusio\Engine\Action\Resolver\DatabaseAction
     */
    protected static function getDatabaseActionService($container)
    {
        return $container->privates['Fusio\\Engine\\Action\\Resolver\\DatabaseAction'] = new \Fusio\Engine\Action\Resolver\DatabaseAction(($container->privates['Fusio\\Engine\\Repository\\ActionMemory'] ??= new \Fusio\Engine\Repository\ActionMemory()));
    }

    /**
     * Gets the private 'Fusio\Engine\Action\Runtime' shared autowired service.
     *
     * @return \Fusio\Engine\Action\Runtime
     */
    protected static function getRuntimeService($container)
    {
        $a = ($container->privates['Fusio\\Engine\\Factory\\Action'] ?? self::getActionService($container));

        if (isset($container->privates['Fusio\\Engine\\Action\\Runtime'])) {
            return $container->privates['Fusio\\Engine\\Action\\Runtime'];
        }

        $instance = new \Fusio\Engine\Action\Runtime(new \Fusio\Engine\Connector(($container->privates['Fusio\\Engine\\Repository\\ConnectionMemory'] ??= new \Fusio\Engine\Repository\ConnectionMemory()), ($container->privates['Fusio\\Engine\\Factory\\Connection'] ?? self::getConnectionService($container))), new \Fusio\Engine\Response\Factory(), new \Fusio\Engine\Processor(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Fusio\\Engine\\Action\\Resolver\\DatabaseAction'] ?? self::getDatabaseActionService($container));
            yield 1 => ($container->privates['Fusio\\Engine\\Action\\Resolver\\PhpClass'] ??= new \Fusio\Engine\Action\Resolver\PhpClass());
        }, 2), $a, ($container->privates['Fusio\\Engine\\Action\\MemoryQueue'] ??= new \Fusio\Engine\Action\MemoryQueue())), new \Fusio\Engine\Dispatcher(), new \Monolog\Logger('Fusio-Engine', [new \Monolog\Handler\NullHandler()]), new \Symfony\Component\Cache\Psr16Cache(new \Symfony\Component\Cache\Adapter\ArrayAdapter()));

        if (isset($container->privates['Fusio\\Engine\\Action\\Runtime'])) {
            return $container->privates['Fusio\\Engine\\Action\\Runtime'];
        }

        return $container->privates['Fusio\\Engine\\Action\\Runtime'] = $instance;
    }

    /**
     * Gets the private 'Fusio\Engine\Factory\Action' shared autowired service.
     *
     * @return \Fusio\Engine\Factory\Action
     */
    protected static function getActionService($container)
    {
        $instance = new \Fusio\Engine\Factory\Action(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Fusio\\Engine\\Test\\CallbackAction' => ['services', 'Fusio\\Engine\\Test\\CallbackAction', 'getCallbackActionService', false],
            'Fusio\\Adapter\\Http\\Action\\HttpComposition' => ['services', 'Fusio\\Adapter\\Http\\Action\\HttpComposition', 'getHttpCompositionService', false],
            'Fusio\\Adapter\\Http\\Action\\HttpLoadBalancer' => ['services', 'Fusio\\Adapter\\Http\\Action\\HttpLoadBalancer', 'getHttpLoadBalancerService', false],
            'Fusio\\Adapter\\Http\\Action\\HttpProcessor' => ['services', 'Fusio\\Adapter\\Http\\Action\\HttpProcessor', 'getHttpProcessorService', false],
            'Fusio\\Adapter\\Http\\Action\\HttpRaw' => ['services', 'Fusio\\Adapter\\Http\\Action\\HttpRaw', 'getHttpRawService', false],
        ], [
            'Fusio\\Engine\\Test\\CallbackAction' => 'Fusio\\Engine\\Test\\CallbackAction',
            'Fusio\\Adapter\\Http\\Action\\HttpComposition' => 'Fusio\\Adapter\\Http\\Action\\HttpComposition',
            'Fusio\\Adapter\\Http\\Action\\HttpLoadBalancer' => 'Fusio\\Adapter\\Http\\Action\\HttpLoadBalancer',
            'Fusio\\Adapter\\Http\\Action\\HttpProcessor' => 'Fusio\\Adapter\\Http\\Action\\HttpProcessor',
            'Fusio\\Adapter\\Http\\Action\\HttpRaw' => 'Fusio\\Adapter\\Http\\Action\\HttpRaw',
        ]));

        if (isset($container->privates['Fusio\\Engine\\Factory\\Action'])) {
            return $container->privates['Fusio\\Engine\\Factory\\Action'];
        }

        return $container->privates['Fusio\\Engine\\Factory\\Action'] = $instance;
    }

    /**
     * Gets the private 'Fusio\Engine\Factory\Connection' shared autowired service.
     *
     * @return \Fusio\Engine\Factory\Connection
     */
    protected static function getConnectionService($container)
    {
        return $container->privates['Fusio\\Engine\\Factory\\Connection'] = new \Fusio\Engine\Factory\Connection(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Fusio\\Engine\\Test\\CallbackConnection' => ['services', 'Fusio\\Engine\\Test\\CallbackConnection', 'getCallbackConnectionService', false],
            'Fusio\\Adapter\\Http\\Connection\\Http' => ['services', 'Fusio\\Adapter\\Http\\Connection\\Http', 'getHttpService', false],
        ], [
            'Fusio\\Engine\\Test\\CallbackConnection' => 'Fusio\\Engine\\Test\\CallbackConnection',
            'Fusio\\Adapter\\Http\\Connection\\Http' => 'Fusio\\Adapter\\Http\\Connection\\Http',
        ]));
    }
}
